services:
  chika:
    build:
      context: .
      dockerfile: app.dockerfile
    volumes:
      - /app/node_modules
  ollama:
    image: ollama/ollama:0.5.7
    ports:
      - ${OLLAMA_PORT}:${OLLAMA_PORT}
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_MODEL=$OLLAMA_MODEL
      - GIN_MODE=$OLLAMA_MODE
      - OLLAMA_COOLDOWN_IN_SECONDS=$OLLAMA_COOLDOWN_IN_SECONDS
    entrypoint: ['/bin/sh', '/root/.ollama/scripts/startup.sh']