services:
  chika:
    build:
      context: .
      dockerfile: app.dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
      - /app/node_modules
  ollama:
    image: ollama/ollama:0.5.7
    ports:
      - ${OLLAMA_PORT}:${OLLAMA_PORT}
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_MODEL=$OLLAMA_MODEL
      - GIN_MODE=$OLLAMA_MODE
      - OLLAMA_COOLDOWN_IN_SECONDS=$OLLAMA_COOLDOWN_IN_SECONDS
      - NVIDIA_VISIBLE_DEVICES=all
      - OLLAMA_GPU=true
      - OLLAMA_BATCH_SIZE=512
      - OLLAMA_PARALLELISM=8 
      - OLLAMA_CTX_SIZE=512
      - OLLAMA_THREADS=4
      - OLLAMA_KEEP_ALIVE=$OLLAMA_KEEP_ALIVE
    entrypoint: ['/bin/sh', '/root/.ollama/scripts/startup.sh']
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['all']
            capabilities: [gpu]
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    volumes:
      - open-webui:/app/backend/data
volumes:
  ollama:
  open-webui: